$ python test_with_mox.py

.F
======================================================================
FAIL: test2 (__main__.UsingMoxDatetimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/mox.py", line 1868, in new_method
    func(self, *args, **kwargs)
  File "test_with_mox.py", line 26, in test2
    self.assertEqual(self._callFUT(), 10)
AssertionError: <mox.MockMethod object at 0x9cf170c> != 10

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (failures=1)
